### ISSUE TITLE
Why `ureq` when `reqwest` is already used?

### ISSUE THREAD

**Issue by jirutka** [hrkfdn/ncspot#1128]
This project already depends on `reqwest`, so why adding another HTTP client library when `rspotify` supports `reqwest`?

```toml
[dependencies.rspotify]
default-features = false
features = ["client-ureq", "ureq-rustls-tls"]
version = "0.11.5"
```
